---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: hive-db-credentials
  namespace: data-platform
spec:
  encryptedData:
    password: AgA6s8ok408EMBU7sxzp8Jpu/kfKDIlP/yxY5xUUNmTJdysE38IgNfc1lTWrZOwfkjSw+6l4TwiMIyTERNY4ZsmzRZrSr/cK4K5rRnQ+1dgTWm1arpeuA9c/4Z2KxAG0dsWl42SiVIJjOIzx7DStTrvphx6s619+ZbgAKp1lWbCU8YA+Ajc9ztI63q9X4xUrV5nXdcYwi2739O3uSoQR8gEXd+usItDeQq1nhrKyKNsDINMWDp8Gw53UlZUxbZJIjh4MPWPjEmuxygQWZpjaYwkAOiBL3ToH+UbelPY7/INiJuYlGtupEXtLzbcTx9Io5riX6OYa83LeXsG6Omw13AKeeRqacDItZsFBN1Vs2nhRN+Obc+fnqk+OT853tjKX4AubWn51YVU7r92MQa2iITw4XRVeTZNdH/Ly9ZypcmdYy2xWLhOTym34cad8rxxqIxts3bUd0oUbuU3rHdS1wjPCoDZsg2JHbz3guWUObvxkFf8HuglyrZ9a+Yu2KZdTj7k+p1YsvfIlMXmqYR9V47BDdGVlQkmq7FoiXG37gLrxw/+hcu8rfXd1+enQ/Zkwe9LHv9x/ZtSSM4s56/KSNiz34ov402Li+lxj22HUei3hjM4pzcbxFSKjqpbvxeWQGkF7FCn0vYyt5zz1NS0aHDbF4tOj8Pd4o+XMdu5XIFuA+Q1E3gKJ12VR9R4ZCbwf0uQZL3GI
    username: AgAOLH6/27auoYfL/UJO5/MPF5WN/nKW5atTIlpQzyLWpZMxkCR/Qq1QiN4B0buw45iBieBP6t5AsZcGaXf+p5LFpVKrrk/dIOZZpMlmPvpDbOcTzfyhOskfHkEwal/S2Gw9YRTbLLp9Kvvx7FGkEkeyPJbUaupRsutzhqgN8qPCRW05QMilPWG4uZAeabC82p1mkIo4BfNHvxqmMvZnD/qj01YSzrHGva2FR7k8nHvbEqjWS91Czaz9mJjzsLA1sGmHm+Ke8l9ddNVrK0uVQwrNKhVKwN56AiiYgRjcbYzXSvrkiKdhw03L+pcgFObrLtGSQ/Mc3AvBNgw5VEnAnriAOwliE3yRmMQF3iOkshOop43x3BPHI3Z4Xrk1J0k1MV9wQjnEfv81vY2428WqoqSoiaKjSr76SCR97oldyEAnavk6cVKJURNcWxNqDLa7LUvHDOIXUHhsdgVQdYi25Ozq53Qmli1LiQ2KSmE09MpY6m3H7nJkDBnn+++lyhRQEh58cY+Ka04Speya8hCGCi6k/p5G7Dy089zczy8cwI95ZNCAY2TxefUbXkHKXMpNJlk0fYxuaUoe98W4+LHCtEOr+yem7IJrZN4XEkuVU1iQjTJ5AvOBMPW4UtCWj7s83effw682wipi2YJqnJAANmj8qOPHSN4DvR4k9vHYn+Mx11mc7BnN9DUklSU8gTFyXISWxVh5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: hive-db-credentials
      namespace: data-platform
    type: Opaque
