---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: hive-minio-credentials
  namespace: data-platform
spec:
  encryptedData:
    accessKey: AgApzhAi+bg7LPGMwm1lBjM1ZVWlAZZtLEWSA88Z0hP4Pk1inA3UVTl7ph+tW7sJs3u/VjUu2gZLZIXCIq7ohfjx7mT/ra7I+B9eUY9EzHmHY06LLTnl2cdqrtUfod6jT4HWcTewfeDrfpFfoUjGZI3uudwmKjlfrd3dSnP/cy78RTjeeJMTNo8uWzhPHBesTXuGsQxM0YmT+a4LDtWHRgP2q9qngaJI85cDn21vpkV9/ceqni16vFc1eofZ/hc+5/rcsZ4iA5HcG4y/1fQHEGg3VuAvCNuPW5NZ1BZ8FerywqAvWMNuTZBqn5orwEwDHsYD2v0Tsjo7dFDrOVCYJYV/g7pk71gvXRa9JO0tbG7lOo18zbYJeA1iDlUl19EG59mqMIw0lTpzzo+QZMhB/hydHv9Y0EfsJdy78v77uiWux35J7VtvNFJpcj7eC9aKkEN/cg4rdQgmTTaP2rVEwYhOgWsxQKJ7SNTyGVJV+lvKndbrATI6Ur9TDTRzHis5pD/5CpHTXqF2jwQeKjPd4PcsglS6r/xhs+MF2C5zbwRC6elb1sE6XRBUZkTw4M1UXZBFVbA3yb86CnkItRjF37UPiPN9H+Dz5hLzGZjGx7jx4gOMl49UykEmYEn42cWlss3Jj3tDY8pfjRu/lXD193LYrm1WVNm+o4F2DujVN9bBbGaJee7HHjpBU10cxa0jD8DTTGRv
    secretKey: AgA/VHhQv72+xQaQ/6tbc9v6x1/fIslhZeo5y1mI1GqZ0dwWfS1tDJbd7JkgL84mlnug6IchxZ1TLrq2d3doDqO2/JHjG3SlFC5X2MHjj2nSp4ltkHZoFgCp3cn8aWZWYdf78DbCqRvn9fM3bLFlbnY5BW/JqnSdd+reTnCvwNwJ/3NZMZfcDUSlAdbqd3Qy9ickmx7+pces/B6z0ugXWzhHr4dAOlem4KZtQxIxDq8dBDA6N0d4HFvC7nWcrJr9vCsh6gKoKIQbsxClhb/zUUytKNxPjojBDr7/Z1fcbkazHV8v7QbYaeMsh34rywZQMkMpMvAh3JpBLhqoWqDi5Ajwh/XXl+ERJHza9UmRBnGB6+JXRAtkthZOvexnIZBVA9BoZh80QuU7i4vDeApBV7//5LVd+gXxNB6dqRLXWooVJuQ8zxUHsV+z7KpxIUEflRDNkCWOj/2EcC/Kv2G2i6ebylwrEil4imgdSWlyOqtXrn68jIrM6VXBDSbxbo9ddoVB37M96UdWCN3N+X29hAYbcK8rwixHWOXdnurlsFJVRSBsXPHok0+LNkLKKjYBAGEZX+3tLy3nF9SscJ5peXmunlEdcBiq70Zdei2y3+LZKMekupEyCOCtiaGyh0lG2MVW6tStvL1xqOVZ6GIVQD3eFXFpgHfRBKV0afAckrv0b94kaC9WqYX5dXWNRx17+iPRmm7558X3TIKQ7dR5kyo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        secrets.stackable.tech/class: hive-s3-secret-class
      name: hive-minio-credentials
      namespace: data-platform
    type: Opaque
