---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-connections
  namespace: data-platform
spec:
  encryptedData:
    AIRFLOW_CONN_MINIO_DEFAULT: AgBJ7HesyaSfaIZUiyCqZm3+Bej81JDPJfhFmdFu07AAsndwhLInB22t+ZP3Cvi8SR2oTmHht3sIi1mp/Q5EcWfGfkOHPC/rwdvuRRzJJG8Hc+oK+NyarL5kxXrF7MIev9w48aZQihvsnNAL+0AR0YprmYVAX89wKxExxlr2jlg+L6KEH/MWQU+Zbhex92TSiCa2t7DuEPI79drWFeJjpOzbqSUStEhxIGcATz31Df3EL1eJX6mwJCBLErUFMqsEF3C0w2UUVTFVVf/oWoeLUb/cnvfwZIP7yosOK5PrDOh6yzYHrc9RG7G90qjfynoFeorpPYqCOZGEYXR6GUq0cSiKMf7tKGJajppib1LEGIZpsXfUTZNgjdX/k3LfOhLtPtbY5dY/uAEPJ4pQf1MDblSPpbRMAnxZnX4CLB1QSZ2jCx0iP/C3PkDT+JYMpkEFSSqevzsVw3FNRnUdD6+7q4945lGNbeRSlDWExxyXdSBhxZmPNBlfPDq4o2jezqZG3JEex91AFwFXmWFa52GCMgR3HK9Cm8pRKi87QLqz+ilvr/Riu0aln1NwuVTBVebeTBWuMIB1vkNuEtSDpzkQR/M/pYpSKYw4HrQB93hTt1XjrHQ8E+aBn1H/HKm5s0DFOTB7g96zWTKpFsbIaXO9RVYHFEozupx6Jht1JiQ7cDaCd0v7VIeT0CapZpsNAs4cBmw8ZMUXXZI/aCFw3/uxa/QMvJM6MZ/M/lGadtGwVmPYGjVJAErjxtOkqmeWHPZEXN5W+arENEBlf1heVUbsD7ARNxecXqueNeiyz4KuMEJRKQKCs3s8SS+Ti0+2sJTkJgrfUdmcZh8GV3QeBvJJi4FsLmoZkM4xQ+nrZ/eM8HSs1xy+7lOCGcu3MhX6UDI1jFngRq9qxXxosEvBtZPu1o4maMfW558vtPgF0tH/MZ0ynh2IVaMBOilthPV6hKm8gJsMRw==
  template:
    metadata:
      name: airflow-connections
      namespace: data-platform
